-- ClipShare v2 — WebRTC P2P mode
--
-- NO DATABASE TABLES NEEDED.
--
-- ClipShare now uses Supabase Realtime channels ONLY for the initial
-- WebRTC handshake (3 tiny SDP messages, ~1 KB total per connection).
-- All clipboard data travels directly between browsers via WebRTC (P2P).
-- Nothing is stored — the signalling messages are transient WebSocket events.
--
-- Realtime channels are enabled by default on every Supabase project.
-- You don't need to run any SQL.
--
-- ────────────────────────────────────────────────────────────────────────────
-- If you created the old clipboard_rooms table from v1, clean it up:
-- ────────────────────────────────────────────────────────────────────────────
-- DROP TABLE IF EXISTS clipboard_rooms;
